'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { ApiError,type Client } from './client';
import { accountOperationStatus,automationProjection,type AccountOperationStatus,type AutomationProjection,type AutomationSettings } from './automation-model';
import { AutomationRealm } from './AutomationRealm';
import { TrustedFill } from './TrustedFill';

type Draft=Pick<AutomationSettings,'enabled'|'automaticAccountCreation'|'passwordStrategy'>&{signupEmail:string};
const draftFor=(value:AutomationSettings):Draft=>({enabled:value.enabled,automaticAccountCreation:value.automaticAccountCreation,passwordStrategy:value.passwordStrategy,signupEmail:''});
export function Automation({client,dirtyChanged}:{client:Client;dirtyChanged(value:boolean):void}) {
  const [data,setData]=useState<AutomationProjection|null>(null),[draft,setDraft]=useState<Draft|null>(null),[operation,setOperation]=useState<AccountOperationStatus|null>(null);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [realmUrl,setRealmUrl]=useState(''),[realmEmail,setRealmEmail]=useState(''),[trustedDirty,setTrustedDirty]=useState(false);
  const [addingRealm,setAddingRealm]=useState(false);
  const [dirtyRealms,setDirtyRealms]=useState<Set<string>>(()=>new Set());
  const conflict=useRef<HTMLDivElement>(null), request=useRef<AbortController|null>(null);
  const dirty=Boolean(data&&draft&&(draft.enabled!==data.settings.enabled||draft.automaticAccountCreation!==data.settings.automaticAccountCreation||draft.passwordStrategy!==data.settings.passwordStrategy||draft.signupEmail));
  const allDirty=dirty||Boolean(realmUrl||realmEmail)||trustedDirty||dirtyRealms.size>0;
  useEffect(()=>{dirtyChanged(allDirty||busy);return()=>dirtyChanged(false);},[allDirty,busy,dirtyChanged]);
  const realmDirtyChanged=useCallback((id:string,value:boolean)=>setDirtyRealms(current=>{const next=new Set(current);if(value)next.add(id);else next.delete(id);return next;}),[]);
  const refresh=useCallback(async(quiet=false,preserveDraft=false)=>{request.current?.abort();const controller=new AbortController();request.current=controller;setLoading(true);setError('');try{
    const [projectionValue,operationValue]=await Promise.all([client.automationRequest('/api/automation','GET',undefined,controller.signal),client.automationRequest('/api/account-operation','GET',undefined,controller.signal)]);
    const projection=automationProjection(projectionValue);setData(projection);if(!preserveDraft)setDraft(draftFor(projection.settings));setOperation(accountOperationStatus(operationValue));if(!quiet)setNotice('Automation controls refreshed.');
  }catch(failure){if(!controller.signal.aborted)setError(failure instanceof Error?failure.message:'Unable to load automation controls.');}finally{if(!controller.signal.aborted)setLoading(false);}},[client]);
  useEffect(()=>{void refresh(true);return()=>request.current?.abort();},[refresh]);
  async function mutate(action:()=>Promise<unknown>,success:string,preserveDraft=false){if(busy)return;setBusy(true);setError('');setNotice('');try{await action();await refresh(true,preserveDraft);setNotice(success);}catch(failure){
    if(failure instanceof ApiError&&failure.code==='revision_conflict'){setError('Automation data changed elsewhere. Nothing was retried. Refresh and review the latest revision.');requestAnimationFrame(()=>conflict.current?.focus());}
    else setError(failure instanceof Error?failure.message:'Automation operation failed.');
  }finally{setBusy(false);}}
  function save(event:React.FormEvent){event.preventDefault();if(!data||!draft)return;const patch:Record<string,unknown>={enabled:draft.enabled,automaticAccountCreation:draft.automaticAccountCreation,passwordStrategy:draft.passwordStrategy};if(draft.signupEmail.trim())patch.signupEmail=draft.signupEmail.trim();void mutate(()=>client.automationRequest('/api/automation/settings','PATCH',{patch,expectedRevision:data.settings.revision}),'Automation settings saved.');}
  function clearEmail(){if(!data)return;void mutate(()=>client.automationRequest('/api/automation/settings','PATCH',{patch:{signupEmail:null},expectedRevision:data.settings.revision}),'Signup email cleared.');}
  function copyProfileEmail(){if(!data)return;void mutate(()=>client.automationRequest('/api/automation/settings/copy-profile-email','POST',{expectedProfileRevision:data.profileRevision,expectedSettingsRevision:data.settings.revision}),'Profile email copied once; future profile edits stay independent.');}
  function addRealm(event:React.FormEvent){event.preventDefault();const payload:Record<string,string>={url:realmUrl};if(realmEmail.trim())payload.signupEmailOverride=realmEmail.trim();void mutate(async()=>{try{
      await client.automationRequest('/api/employer-accounts','POST',payload);
    }catch(failure){
      if(failure instanceof ApiError&&failure.code==='store_rejected'&&failure.message==='employer account realm is unresolved')throw new Error('This portal is not supported for account preparation. Add an exact Workday or Oracle Recruiting job URL.');
      throw failure;
    }setRealmUrl('');setRealmEmail('');setAddingRealm(false);},'Employer portal added.',true);}
  async function refreshOperation(){if(busy)return;setBusy(true);setError('');try{setOperation(accountOperationStatus(await client.automationRequest('/api/account-operation')));}catch(failure){setError(failure instanceof Error?failure.message:'Unable to load account operation.');}finally{setBusy(false);}}
  async function recover(){if(busy)return;setBusy(true);setError('');try{setOperation(accountOperationStatus(await client.automationRequest('/api/account-operation/recover','POST',{})));setNotice('Stranded account operation marked ambiguous.');await refresh(true,true);}catch(failure){setError(failure instanceof Error?failure.message:'Unable to recover account operation.');}finally{setBusy(false);}}
  const flow=data?.capability.accountFlowAutomation;
  return <section className="automation-workspace" aria-labelledby="automation-title">
    <header className="workspace-hero"><div className="workspace-hero-copy"><p className="eyebrow">Controls</p><h1 id="automation-title">Automation</h1><p>Manage how the companion prepares supported employer accounts. Live account creation and final application submission remain unavailable.</p></div><div className="workspace-hero-actions"><button className="secondary" disabled={loading||busy||allDirty} onClick={()=>void refresh()}>Refresh</button></div></header>
    {loading&&!data&&<p className="workspace-status" role="status">Loading automation controls…</p>}
    {notice&&<p className="notice" role="status">{notice}</p>}{error&&<div ref={conflict} tabIndex={-1} className="error" role="alert">{error}</div>}
    {data&&draft&&<><div className="automation-status-strip" aria-label="Automation summary"><span><i className={data.settings.enabled?'is-on':''}/><strong>Account preparation</strong> {data.settings.enabled?'On':'Off'}</span><span><strong>{data.accounts.length}</strong> supported {data.accounts.length===1?'portal':'portals'}</span><span className="automation-safe-status">Live actions off</span></div>
    <div className="automation-grid"><section className="workspace-panel automation-settings-panel" aria-labelledby="automation-settings-heading"><div className="workspace-panel-heading"><div><p className="eyebrow">Account preparation</p><h2 id="automation-settings-heading">Automation settings</h2></div><span className="automation-state">{data.settings.enabled?'On':'Off'}</span></div>
      <div className="automation-capabilities" role="status"><span className={flow?.workdayPasswordAccountReady?'is-available':'is-unavailable'}>{flow?.workdayPasswordAccountReady?'Workday supported':'Workday setup unavailable'}</span><span className={flow?.greenhouseAccountlessClassificationReady?'is-available':'is-unavailable'}>{flow?.greenhouseAccountlessClassificationReady?'Greenhouse needs no account':'Greenhouse status unresolved'}</span><span className={flow?.emailOnlyCandidateProfileReady?'is-available':'is-unavailable'}>{flow?.emailOnlyCandidateProfileReady?'Oracle supported':'Oracle setup unavailable'}</span></div>
      <details className="automation-disclosure"><summary role="button">Change automation settings</summary><div className="automation-disclosure-body"><p className="automation-safety">Settings and recovery remain available while live execution is disabled. Revision {data.settings.revision}.</p><form className="automation-form" onSubmit={save}><fieldset disabled={busy}><legend className="visually-hidden">Automation settings</legend>
        <label className="check-row"><input type="checkbox" checked={draft.enabled} onChange={event=>setDraft({...draft,enabled:event.target.checked})}/><span><strong>Enable companion automation controls</strong><small>Expose reviewed account preparation controls inside this local workspace.</small></span></label>
        <label className="check-row"><input type="checkbox" checked={draft.automaticAccountCreation} onChange={event=>setDraft({...draft,automaticAccountCreation:event.target.checked})}/><span><strong>Allow protected account preparation</strong><small>Live execution still requires separately composed authority.</small></span></label>
        <label>Global signup email<input type="email" autoComplete="email" value={draft.signupEmail} placeholder={data.settings.signupEmailConfigured?'Configured; enter a replacement':'Not configured'} onChange={event=>setDraft({...draft,signupEmail:event.target.value})}/><small>{data.settings.signupEmailConfigured?'Configured; value remains hidden':'Not configured'}</small></label>
        <label>Password strategy<select value={draft.passwordStrategy} onChange={event=>setDraft({...draft,passwordStrategy:event.target.value as Draft['passwordStrategy']})}><option value="unique_per_realm">Unique per employer realm</option><option value="shared">Shared credential version</option><option value="custom">Custom per realm</option><option value="ask_each_time">Ask each time</option></select></label>
        <div className="button-row"><button className="primary" disabled={!dirty}>Save settings</button><button className="secondary" type="button" disabled={dirty} onClick={copyProfileEmail}>Copy profile email once</button><button className="text-action" type="button" disabled={dirty||!data.settings.signupEmailConfigured} onClick={clearEmail}>Clear signup email</button></div>
      </fieldset></form><p className="automation-safety">Copying creates a one-time snapshot. Later profile edits do not change the signup email, and the copied value is never returned.</p></div></details>
    </section>
    <section className="workspace-panel automation-realms-panel" aria-labelledby="automation-realms-heading"><div className="workspace-panel-heading"><div><p className="eyebrow">Employer portals</p><h2 id="automation-realms-heading">Supported portals</h2></div><button className="secondary compact-action" type="button" onClick={()=>setAddingRealm(value=>!value)}>{addingRealm?'Cancel':'Add portal'}</button></div>
      {addingRealm&&<div className="automation-add-realm"><form className="automation-form realm-form" onSubmit={addRealm}><fieldset disabled={busy}><legend className="visually-hidden">Add employer portal</legend><label>Exact employer portal URL<input type="url" required value={realmUrl} placeholder="Workday or Oracle Recruiting job URL" onChange={event=>setRealmUrl(event.target.value)}/></label><label>Optional signup email override<input type="email" autoComplete="email" value={realmEmail} onChange={event=>setRealmEmail(event.target.value)}/></label><button className="primary">Add employer portal</button></fieldset></form><p className="automation-safety">Unknown hosts and unproven portal paths are rejected.</p></div>}
      {data.accounts.length?<div className="automation-accounts" role="list">{data.accounts.map(account=><AutomationRealm key={account.realmRef} account={account} client={client} disabled={busy} dirtyChanged={realmDirtyChanged} changed={()=>refresh(true,true)}/>)}</div>:<div className="workspace-empty"><strong>No supported portals added yet.</strong><span>Add an exact Workday or Oracle Recruiting job URL when you need account preparation.</span></div>}
    </section>
    <section className={`workspace-panel operation-panel${operation?.status==='recovery_required'?' needs-recovery':''}`} aria-labelledby="account-operation-heading"><div className="workspace-panel-heading"><div><p className="eyebrow">Recovery</p><h2 id="account-operation-heading">Account operation</h2></div><span className="automation-state">{operation?.status==='recovery_required'?'Action needed':'Clear'}</span></div>{operation?.status==='recovery_required'?<><p className="notice" role="status">Recovery required · {operation.operation.stage.replaceAll('_',' ')} · portal {operation.operation.realmRef.slice(0,12)}…</p><p className="automation-safety">Recovery records the outcome as ambiguous. It cannot retry, rotate credentials, or provision the account again.</p><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>void refreshOperation()}>Refresh status</button><button className="trash-delete" disabled={busy} onClick={()=>void recover()}>Mark operation ambiguous</button></div></>:<details className="automation-disclosure compact-disclosure"><summary>Recovery tools</summary><div className="automation-disclosure-body"><p className="automation-safety">No protected account operation is pending. Recovery never infers success.</p><button className="secondary" disabled={busy} onClick={()=>void refreshOperation()}>Refresh status</button></div></details>}</section>
    <details className="automation-advanced"><summary><span><strong>Trusted Fill approvals</strong><small>Advanced controls for exact, non-final field operations</small></span><span className="automation-state">No final action</span></summary><TrustedFill client={client} disabled={busy} dirtyChanged={setTrustedDirty}/></details></div></>}
  </section>;
}
