'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { ApiError,type Client } from './client';
import { accountOperationStatus,automationProjection,type AccountOperationStatus,type AutomationProjection,type AutomationSettings } from './automation-model';
import { AutomationRealm } from './AutomationRealm';
import { TrustedFill } from './TrustedFill';

type Draft=Pick<AutomationSettings,'enabled'|'automaticAccountCreation'|'passwordStrategy'>&{signupEmail:string};
const draftFor=(value:AutomationSettings):Draft=>({enabled:value.enabled,automaticAccountCreation:value.automaticAccountCreation,passwordStrategy:value.passwordStrategy,signupEmail:''});
export function Automation({client,dirtyChanged}:{client:Client;dirtyChanged(value:boolean):void}) {
  const [data,setData]=useState<AutomationProjection|null>(null),[draft,setDraft]=useState<Draft|null>(null),[operation,setOperation]=useState<AccountOperationStatus|null>(null);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [realmUrl,setRealmUrl]=useState(''),[realmEmail,setRealmEmail]=useState(''),[trustedDirty,setTrustedDirty]=useState(false);
  const [dirtyRealms,setDirtyRealms]=useState<Set<string>>(()=>new Set());
  const conflict=useRef<HTMLDivElement>(null), request=useRef<AbortController|null>(null);
  const dirty=Boolean(data&&draft&&(draft.enabled!==data.settings.enabled||draft.automaticAccountCreation!==data.settings.automaticAccountCreation||draft.passwordStrategy!==data.settings.passwordStrategy||draft.signupEmail));
  const allDirty=dirty||Boolean(realmUrl||realmEmail)||trustedDirty||dirtyRealms.size>0;
  useEffect(()=>{dirtyChanged(allDirty||busy);return()=>dirtyChanged(false);},[allDirty,busy,dirtyChanged]);
  const realmDirtyChanged=useCallback((id:string,value:boolean)=>setDirtyRealms(current=>{const next=new Set(current);if(value)next.add(id);else next.delete(id);return next;}),[]);
  const refresh=useCallback(async(quiet=false,preserveDraft=false)=>{request.current?.abort();const controller=new AbortController();request.current=controller;setLoading(true);setError('');try{
    const [projectionValue,operationValue]=await Promise.all([client.automationRequest('/api/automation','GET',undefined,controller.signal),client.automationRequest('/api/account-operation','GET',undefined,controller.signal)]);
    const projection=automationProjection(projectionValue);setData(projection);if(!preserveDraft)setDraft(draftFor(projection.settings));setOperation(accountOperationStatus(operationValue));if(!quiet)setNotice('Automation controls refreshed.');
  }catch(failure){if(!controller.signal.aborted)setError(failure instanceof Error?failure.message:'Unable to load automation controls.');}finally{if(!controller.signal.aborted)setLoading(false);}},[client]);
  useEffect(()=>{void refresh(true);return()=>request.current?.abort();},[refresh]);
  async function mutate(action:()=>Promise<unknown>,success:string,preserveDraft=false){if(busy)return;setBusy(true);setError('');setNotice('');try{await action();await refresh(true,preserveDraft);setNotice(success);}catch(failure){
    if(failure instanceof ApiError&&failure.code==='revision_conflict'){setError('Automation data changed elsewhere. Nothing was retried. Refresh and review the latest revision.');requestAnimationFrame(()=>conflict.current?.focus());}
    else setError(failure instanceof Error?failure.message:'Automation operation failed.');
  }finally{setBusy(false);}}
  function save(event:React.FormEvent){event.preventDefault();if(!data||!draft)return;const patch:Record<string,unknown>={enabled:draft.enabled,automaticAccountCreation:draft.automaticAccountCreation,passwordStrategy:draft.passwordStrategy};if(draft.signupEmail.trim())patch.signupEmail=draft.signupEmail.trim();void mutate(()=>client.automationRequest('/api/automation/settings','PATCH',{patch,expectedRevision:data.settings.revision}),'Automation settings saved.');}
  function clearEmail(){if(!data)return;void mutate(()=>client.automationRequest('/api/automation/settings','PATCH',{patch:{signupEmail:null},expectedRevision:data.settings.revision}),'Signup email cleared.');}
  function copyProfileEmail(){if(!data)return;void mutate(()=>client.automationRequest('/api/automation/settings/copy-profile-email','POST',{expectedProfileRevision:data.profileRevision,expectedSettingsRevision:data.settings.revision}),'Profile email copied once; future profile edits stay independent.');}
  function addRealm(event:React.FormEvent){event.preventDefault();const payload:Record<string,string>={url:realmUrl};if(realmEmail.trim())payload.signupEmailOverride=realmEmail.trim();void mutate(async()=>{await client.automationRequest('/api/employer-accounts','POST',payload);setRealmUrl('');setRealmEmail('');},'Resolved employer realm added.',true);}
  async function refreshOperation(){if(busy)return;setBusy(true);setError('');try{setOperation(accountOperationStatus(await client.automationRequest('/api/account-operation')));}catch(failure){setError(failure instanceof Error?failure.message:'Unable to load account operation.');}finally{setBusy(false);}}
  async function recover(){if(busy)return;setBusy(true);setError('');try{setOperation(accountOperationStatus(await client.automationRequest('/api/account-operation/recover','POST',{})));setNotice('Stranded account operation marked ambiguous.');await refresh(true,true);}catch(failure){setError(failure instanceof Error?failure.message:'Unable to recover account operation.');}finally{setBusy(false);}}
  const flow=data?.capability.accountFlowAutomation;
  return <section className="automation-workspace" aria-labelledby="automation-title">
    <header className="workspace-hero"><div className="workspace-hero-copy"><p className="eyebrow">Companion automation</p><h1 id="automation-title">Account controls that fail closed.</h1><p>Review redacted settings, tenant metadata, and protected-operation recovery. No live execution control or final application action is reachable here.</p></div><div className="workspace-hero-actions"><button className="secondary" disabled={loading||busy||allDirty} onClick={()=>void refresh()}>Refresh automation</button></div></header>
    {loading&&!data&&<p className="workspace-status" role="status">Loading automation controls…</p>}
    {notice&&<p className="notice" role="status">{notice}</p>}{error&&<div ref={conflict} tabIndex={-1} className="error" role="alert">{error}</div>}
    {data&&draft&&<><div className="automation-metrics" aria-label="Automation summary"><div><strong>{data.accounts.length}</strong><span>Employer realms</span></div><div><strong>{data.settings.enabled?'On':'Off'}</strong><span>Companion controls</span></div><div><strong>{flow?.liveExecutionEnabled?'On':'Off'}</strong><span>Live execution</span></div></div>
    <div className="automation-grid"><section className="workspace-panel automation-settings-panel" aria-labelledby="automation-settings-heading"><div className="workspace-panel-heading"><div><p className="eyebrow">Control plane</p><h2 id="automation-settings-heading">Automation settings</h2></div><span className="facts-revision">Revision {data.settings.revision}</span></div>
      <p className="automation-capability" role="status">{flow?.workdayPasswordAccountReady?'Reviewed Workday seam ready':'Workday account automation unavailable'} · {flow?.greenhouseAccountlessClassificationReady?'Ordinary Greenhouse applications are accountless':'Greenhouse account status unresolved'} · {flow?.emailOnlyCandidateProfileReady?'Oracle candidate-profile seam ready':'Oracle candidate-profile seam unavailable'} · {data.capability.reasonCode.replaceAll('_',' ')}. Settings and recovery remain available; live execution is disabled.</p>
      <form className="automation-form" onSubmit={save}><fieldset disabled={busy}><legend className="visually-hidden">Automation settings</legend>
        <label className="check-row"><input type="checkbox" checked={draft.enabled} onChange={event=>setDraft({...draft,enabled:event.target.checked})}/><span><strong>Enable companion automation controls</strong><small>Expose reviewed account preparation controls inside this local workspace.</small></span></label>
        <label className="check-row"><input type="checkbox" checked={draft.automaticAccountCreation} onChange={event=>setDraft({...draft,automaticAccountCreation:event.target.checked})}/><span><strong>Allow protected account preparation</strong><small>Live execution still requires separately composed authority.</small></span></label>
        <label>Global signup email<input type="email" autoComplete="email" value={draft.signupEmail} placeholder={data.settings.signupEmailConfigured?'Configured; enter a replacement':'Not configured'} onChange={event=>setDraft({...draft,signupEmail:event.target.value})}/><small>{data.settings.signupEmailConfigured?'Configured; value remains hidden':'Not configured'}</small></label>
        <label>Password strategy<select value={draft.passwordStrategy} onChange={event=>setDraft({...draft,passwordStrategy:event.target.value as Draft['passwordStrategy']})}><option value="unique_per_realm">Unique per employer realm</option><option value="shared">Shared credential version</option><option value="custom">Custom per realm</option><option value="ask_each_time">Ask each time</option></select></label>
        <div className="button-row"><button className="primary" disabled={!dirty}>Save settings</button><button className="secondary" type="button" disabled={dirty} onClick={copyProfileEmail}>Copy profile email once</button><button className="text-action" type="button" disabled={dirty||!data.settings.signupEmailConfigured} onClick={clearEmail}>Clear signup email</button></div>
      </fieldset></form><p className="automation-safety">Copying is an explicit one-time snapshot. Later profile edits do not change the signup email, and the copied value is never returned.</p>
    </section>
    <section className="workspace-panel automation-realms-panel" aria-labelledby="automation-realms-heading"><div className="workspace-panel-heading"><div><p className="eyebrow">Employer realms</p><h2 id="automation-realms-heading">Tenant-scoped account metadata</h2></div></div>
      <form className="automation-form realm-form" onSubmit={addRealm}><fieldset disabled={busy}><legend className="visually-hidden">Add employer realm</legend><label>Exact employer portal URL<input type="url" required value={realmUrl} placeholder="Workday or Oracle Recruiting job URL" onChange={event=>setRealmUrl(event.target.value)}/></label><label>Optional signup email override<input type="email" autoComplete="email" value={realmEmail} onChange={event=>setRealmEmail(event.target.value)}/></label><button className="primary">Add resolved realm</button></fieldset></form>
      <p className="automation-safety">Unknown hosts and unproven tenant paths are rejected. Employer names and ATS families are never used as a fallback.</p>
      <div className="automation-accounts" role="list">{data.accounts.map(account=><AutomationRealm key={account.realmRef} account={account} client={client} disabled={busy} dirtyChanged={realmDirtyChanged} changed={()=>refresh(true,true)}/>)}{!data.accounts.length&&<div className="workspace-empty"><strong>No employer realms recorded yet.</strong><span>Add an exact supported portal URL to create redacted tenant metadata.</span></div>}</div>
    </section>
    <section className="workspace-panel operation-panel" aria-labelledby="account-operation-heading"><div className="workspace-panel-heading"><div><p className="eyebrow">Protected operation</p><h2 id="account-operation-heading">Account operation recovery</h2></div></div><p className="automation-safety">Recovery never infers success. A stranded operation becomes permanently ambiguous and cannot retry, rotate, or provision again.</p><p className="notice" role="status">{operation?.status==='recovery_required'?`Recovery required · ${operation.operation.stage.replaceAll('_',' ')} · realm ${operation.operation.realmRef.slice(0,12)}…`:'No protected account operation is pending.'}</p><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>void refreshOperation()}>Refresh operation status</button><button className="trash-delete" disabled={busy||operation?.status!=='recovery_required'} onClick={()=>void recover()}>Mark stranded operation ambiguous</button></div></section>
    <TrustedFill client={client} disabled={busy} dirtyChanged={setTrustedDirty}/></div></>}
  </section>;
}
