'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { ApiError,type Client } from './client';
import { accountOperationStatus,automationProjection,type AccountOperationStatus,type AutomationProjection,type AutomationSettings } from './automation-model';
import { AutomationRealm } from './AutomationRealm';
import { TrustedFill } from './TrustedFill';
import { ApplicationAutomation } from './ApplicationAutomation';

function ApplicationAutomationWorkspace({client,dirtyChanged}:{client:Client;dirtyChanged(value:boolean):void}) {
  const [data,setData]=useState<AutomationProjection|null>(null);
  const [loading,setLoading]=useState(true),[error,setError]=useState('');
  const [trustedDirty,setTrustedDirty]=useState(false),[authorityDirty,setAuthorityDirty]=useState(false);
  const request=useRef<AbortController|null>(null),dirty=trustedDirty||authorityDirty;
  useEffect(()=>{dirtyChanged(dirty);return()=>dirtyChanged(false);},[dirty,dirtyChanged]);
  const refresh=useCallback(async()=>{request.current?.abort();const controller=new AbortController();request.current=controller;setLoading(true);setError('');try{
    setData(automationProjection(await client.automationRequest('/api/automation','GET',undefined,controller.signal)));
  }catch(failure){if(!controller.signal.aborted)setError(failure instanceof Error?failure.message:'Unable to load automation controls.');}finally{if(!controller.signal.aborted)setLoading(false);}},[client]);
  useEffect(()=>{void refresh();return()=>request.current?.abort();},[refresh]);
  return <section className="automation-workspace" aria-labelledby="automation-title">
    <header className="workspace-hero"><div className="workspace-hero-copy"><p className="eyebrow">Controls</p><h1 id="automation-title">Automation</h1><p>Choose bounded application filling through final review. Account setup and sign-in readiness have their own workspace; final submission remains manual.</p></div><div className="workspace-hero-actions"><button className="secondary" disabled={loading||dirty} onClick={()=>void refresh()}>Refresh</button></div></header>
    {loading&&!data&&<p className="workspace-status" role="status">Loading automation controls…</p>}{error&&<p className="error" role="alert">{error}</p>}
    {data&&<><div className="automation-status-strip" aria-label="Automation summary"><span><i/><strong>Application authority</strong> Review bounded</span><span className="automation-safe-status">Live actions off</span></div><div className="automation-grid">
      <ApplicationAutomation client={client} authority={data.applicationAuthority} disabled={loading} dirtyChanged={setAuthorityDirty} changed={applicationAuthority=>setData({...data,applicationAuthority})}/>
      <details className="automation-advanced"><summary><span><strong>Trusted Fill approvals</strong><small>Advanced controls for exact, non-final field operations</small></span><span className="automation-state">No final action</span></summary><TrustedFill client={client} disabled={loading} dirtyChanged={setTrustedDirty}/></details>
    </div></>}
  </section>;
}

type Draft=Pick<AutomationSettings,'enabled'|'automaticAccountCreation'|'passwordStrategy'>;
const draftFor=({enabled,automaticAccountCreation,passwordStrategy}:AutomationSettings):Draft=>({enabled,automaticAccountCreation,passwordStrategy});
function AccountsSignIn({client,dirtyChanged}:{client:Client;dirtyChanged(value:boolean):void}) {
  const [data,setData]=useState<AutomationProjection|null>(null),[draft,setDraft]=useState<Draft|null>(null),[operation,setOperation]=useState<AccountOperationStatus|null>(null);
  const [realmUrl,setRealmUrl]=useState(''),[adding,setAdding]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const request=useRef<AbortController|null>(null),conflict=useRef<HTMLDivElement>(null);
  const settingsDirty=Boolean(data&&draft&&(draft.enabled!==data.settings.enabled||draft.automaticAccountCreation!==data.settings.automaticAccountCreation||draft.passwordStrategy!==data.settings.passwordStrategy)),dirty=settingsDirty||Boolean(realmUrl);
  useEffect(()=>{dirtyChanged(dirty||busy);return()=>dirtyChanged(false);},[dirty,busy,dirtyChanged]);
  const refresh=useCallback(async(quiet=false,preserveDraft=false)=>{request.current?.abort();const controller=new AbortController();request.current=controller;setLoading(true);setError('');try{const [projectionValue,operationValue]=await Promise.all([client.automationRequest('/api/automation','GET',undefined,controller.signal),client.automationRequest('/api/account-operation','GET',undefined,controller.signal)]);const projection=automationProjection(projectionValue);setData(projection);if(!preserveDraft)setDraft(draftFor(projection.settings));setOperation(accountOperationStatus(operationValue));if(!quiet)setNotice('Accounts and sign-in status refreshed.');}catch(failure){if(!controller.signal.aborted)setError(failure instanceof Error?failure.message:'Unable to load accounts and sign-in status.');}finally{if(!controller.signal.aborted)setLoading(false);}},[client]);
  useEffect(()=>{void refresh(true);return()=>request.current?.abort();},[refresh]);
  async function mutate(action:()=>Promise<unknown>,success:string,preserveDraft=false){if(busy)return;setBusy(true);setError('');setNotice('');try{await action();await refresh(true,preserveDraft);setNotice(success);}catch(failure){if(failure instanceof ApiError&&failure.code==='revision_conflict'){setError('Account data changed elsewhere. Nothing was retried. Refresh and review the latest revision.');requestAnimationFrame(()=>conflict.current?.focus());}else setError(failure instanceof Error?failure.message:'Account operation failed.');}finally{setBusy(false);}}
  function save(event:React.FormEvent){event.preventDefault();if(!data||!draft)return;void mutate(()=>client.automationRequest('/api/automation/settings','PATCH',{patch:draft,expectedRevision:data.settings.revision}),'Account settings saved.');}
  function add(event?:React.FormEvent,url=realmUrl,clearDraft=true){event?.preventDefault();void mutate(async()=>{try{await client.automationRequest('/api/employer-accounts','POST',{url});}catch(failure){if(failure instanceof ApiError&&failure.code==='store_rejected'&&failure.message==='employer account realm is unresolved')throw new Error('This portal is not supported. Use an exact Workday or Oracle Recruiting job URL; direct Greenhouse applications need no account.');throw failure;}if(clearDraft)setRealmUrl('');setAdding(false);},'Saved account metadata created.',true);}
  function toggleAdding(){if(adding){setRealmUrl('');setAdding(false);return;}setAdding(true);}
  async function refreshOperation(){if(busy)return;setBusy(true);setError('');try{setOperation(accountOperationStatus(await client.automationRequest('/api/account-operation')));}catch(failure){setError(failure instanceof Error?failure.message:'Unable to load account operation.');}finally{setBusy(false);}}
  async function recover(){if(busy)return;setBusy(true);setError('');try{setOperation(accountOperationStatus(await client.automationRequest('/api/account-operation/recover','POST',{})));setNotice('Stranded account operation marked ambiguous.');await refresh(true,true);}catch(failure){setError(failure instanceof Error?failure.message:'Unable to recover account operation.');}finally{setBusy(false);}}
  const flow=data?.capability.accountFlowAutomation,hasMyGreenhouse=data?.accounts.some(account=>account.adapterId==='mygreenhouse');
  return <section className="automation-workspace accounts-workspace" aria-labelledby="accounts-title"><header className="workspace-hero"><div className="workspace-hero-copy"><p className="eyebrow">Controls</p><h1 id="accounts-title">Accounts &amp; Sign-in</h1><p>Manage redacted account metadata and see browser-session readiness separately. Sign-in happens in the browser; this workspace never handles credentials or email codes.</p></div><div className="workspace-hero-actions"><button className="secondary" disabled={loading||busy||dirty} onClick={()=>void refresh()}>Refresh</button></div></header>
    {loading&&!data&&<p className="workspace-status" role="status">Loading accounts and sign-in status…</p>}{notice&&<p className="notice" role="status">{notice}</p>}{error&&<div ref={conflict} tabIndex={-1} className="error" role="alert">{error}</div>}{data&&draft&&<><div className="automation-status-strip" aria-label="Account readiness summary"><span><strong>{data.accounts.length}</strong> saved {data.accounts.length===1?'account':'accounts'}</span><span className="automation-safe-status">Browser sessions not observed</span></div><div className="automation-grid">
      <section className="workspace-panel automation-settings-panel" aria-labelledby="account-settings-heading"><div className="workspace-panel-heading"><div><p className="eyebrow">Configuration</p><h2 id="account-settings-heading">Account preparation</h2></div><span className="automation-state">Revision {data.settings.revision}</span></div><div className="automation-capabilities" role="status"><span className={flow?.workdayPasswordAccountReady?'is-available':'is-unavailable'}>{flow?.workdayPasswordAccountReady?'Workday Keychain ready':'Workday setup unavailable'}</span><span className={flow?.myGreenhousePasswordlessConfigurationReady?'is-available':'is-unavailable'}>{flow?.myGreenhousePasswordlessExecutionReady?'MyGreenhouse browser sign-in ready':'MyGreenhouse configuration only'}</span><span className={flow?.emailOnlyCandidateProfileReady?'is-available':'is-unavailable'}>{flow?.emailOnlyCandidateProfileReady?'Oracle email-only ready':'Oracle setup unavailable'}</span></div>
        <form className="automation-form" onSubmit={save}><fieldset disabled={busy}><legend className="visually-hidden">Account preparation settings</legend><label className="check-row"><input type="checkbox" checked={draft.enabled} onChange={event=>setDraft({...draft,enabled:event.target.checked})}/><span><strong>Enable account preparation controls</strong><small>Configuration does not grant browser authority.</small></span></label><label className="check-row"><input type="checkbox" checked={draft.automaticAccountCreation} onChange={event=>setDraft({...draft,automaticAccountCreation:event.target.checked})}/><span><strong>Allow protected Workday preparation</strong><small>Native execution remains separately unavailable unless explicitly composed.</small></span></label><label>Workday credential strategy<select value={draft.passwordStrategy} onChange={event=>setDraft({...draft,passwordStrategy:event.target.value as Draft['passwordStrategy']})}><option value="unique_per_realm">Unique per employer realm</option><option value="shared">Shared credential version</option><option value="custom">Custom per realm</option><option value="ask_each_time">Ask each time</option></select></label><button className="primary" disabled={!settingsDirty}>Save settings</button></fieldset></form></section>
      <section className="workspace-panel automation-realms-panel" aria-labelledby="saved-accounts-heading"><div className="workspace-panel-heading"><div><p className="eyebrow">Saved metadata</p><h2 id="saved-accounts-heading">Supported accounts</h2></div><button className="secondary compact-action" type="button" onClick={toggleAdding}>{adding?'Cancel':'Add portal'}</button></div>{adding&&<form className="automation-form realm-form" onSubmit={event=>add(event)}><fieldset disabled={busy}><legend className="visually-hidden">Add supported portal</legend><label>Exact employer portal URL<input type="url" required value={realmUrl} placeholder="Workday or Oracle Recruiting job URL" onChange={event=>setRealmUrl(event.target.value)}/></label><button className="primary">Add portal</button></fieldset></form>}{!hasMyGreenhouse&&<div className="account-callout"><div><strong>MyGreenhouse</strong><p>One optional global passwordless account. Browser sign-in remains separate.</p></div><button className="secondary" disabled={busy} onClick={()=>add(undefined,'https://my.greenhouse.io/',false)}>Add MyGreenhouse</button></div>}{data.accounts.length?<div className="automation-accounts" role="list">{data.accounts.map(account=><AutomationRealm key={account.realmRef} account={account} client={client} disabled={busy} changed={()=>refresh(true,true)}/>)}</div>:<div className="workspace-empty"><strong>No account metadata saved.</strong><span>Add an exact supported portal only when account preparation is needed.</span></div>}
        <article className="automation-account account-not-required"><div className="automation-account-heading"><span className="automation-realm-mark" aria-hidden="true">G</span><div><p className="eyebrow">Direct Greenhouse applications</p><h3>Account not required</h3></div><span className="automation-state">Unpersisted</span></div><dl className="account-readiness"><div><dt>Saved account metadata</dt><dd>None</dd></div><div><dt>Browser session</dt><dd>Not needed</dd></div></dl><p>Job-board application URLs stay accountless and never create an employer account record.</p></article></section>
      <section className={`workspace-panel operation-panel${operation?.status==='recovery_required'?' needs-recovery':''}`} aria-labelledby="account-operation-heading"><div className="workspace-panel-heading"><div><p className="eyebrow">Recovery</p><h2 id="account-operation-heading">Account operation</h2></div><span className="automation-state">{operation?.status==='recovery_required'?'Action needed':'Clear'}</span></div>{operation?.status==='recovery_required'?<><p className="notice" role="status">Recovery required · {operation.operation.stage.replaceAll('_',' ')} · account {operation.operation.realmRef.slice(0,12)}…</p><p className="automation-safety">Recovery records an ambiguous outcome. It cannot retry, rotate, provision, or sign in.</p><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>void refreshOperation()}>Refresh status</button><button className="trash-delete" disabled={busy} onClick={()=>void recover()}>Mark operation ambiguous</button></div></>:<><p className="automation-safety">No protected account operation is pending. Recovery never infers success.</p><button className="secondary" disabled={busy} onClick={()=>void refreshOperation()}>Refresh status</button></>}</section>
    </div></>}</section>;
}

export function Automation({mode='automation',...props}:{client:Client;dirtyChanged(value:boolean):void;mode?:'automation'|'accounts'}) {
  return mode==='accounts'?<AccountsSignIn {...props}/>:<ApplicationAutomationWorkspace {...props}/>;
}
