import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

export async function nativeAnswerCleanupBrowser(page, root, cli) {
  const panel = page.getByRole('region', { name: 'Cleanup preview', exact: true });
  await page.getByRole('button', { name: 'Preview cleanup', exact: true }).click();
  await panel.getByText('No clear duplicates found.', { exact: true }).waitFor();
  await cli('answer-put', JSON.stringify({ key: 'cleanup-winner', question: 'Does the applicant have permission to work in this jurisdiction?', state: 'confirmed', value: 'PRIVATE-CLEANUP-BROWSER', fieldClass: 'authorization', sensitivity: 'personal' }), ['--remember-sensitive']);
  await cli('answer-observe', JSON.stringify({ question: 'Is employment authorization available in the country?', state: 'missing', fieldClass: 'authorization', sensitivity: 'personal' }));
  const before = await readFile(join(root, 'answers.json'), 'utf8');
  await page.getByRole('button', { name: 'Preview cleanup', exact: true }).click();
  await panel.getByText('Does the applicant have permission to work in this jurisdiction?', { exact: true }).waitFor();
  await panel.getByText('Is employment authorization available in the country?', { exact: true }).waitFor();
  assert.doesNotMatch(await panel.innerText(), /PRIVATE-CLEANUP-BROWSER|answer-cleanup-v1/);
  assert.equal(await readFile(join(root, 'answers.json'), 'utf8'), before);
  await page.route('**/api/answers/cleanup-preview', route => route.fulfill({ status: 503, body: '{"error":"Preview temporarily unavailable"}', contentType: 'application/json' }));
  await page.getByRole('button', { name: 'Preview cleanup', exact: true }).click();
  await panel.getByRole('alert').waitFor();
  assert.equal(await panel.getByText('Does the applicant have permission to work in this jurisdiction?', { exact: true }).count(), 0);
  await page.unroute('**/api/answers/cleanup-preview');
  await page.getByRole('button', { name: 'Preview cleanup', exact: true }).click();
  await panel.getByText('Does the applicant have permission to work in this jurisdiction?', { exact: true }).waitFor();
  await page.getByLabel('Source', { exact: true }).fill('cleanup-preview-invalidation');
  await page.getByRole('button', { name: 'Save answer', exact: true }).click();
  await page.getByText('Answer saved.', { exact: true }).waitFor();
  await panel.getByText('Does the applicant have permission to work in this jurisdiction?', { exact: true }).waitFor({ state: 'hidden' });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await page.getByRole('button', { name: 'Preview cleanup', exact: true }).click();
  await panel.getByRole('button', { name: 'Approve merge', exact: true }).waitFor();
  const premerge = await readFile(join(root, 'answers.json'), 'utf8');
  page.once('dialog', dialog => dialog.dismiss());
  await panel.getByRole('button', { name: 'Approve merge', exact: true }).click();
  assert.equal(await readFile(join(root, 'answers.json'), 'utf8'), premerge);
  await page.getByLabel('Source', { exact: true }).fill('unsaved merge guard');
  assert.equal(await panel.getByRole('button', { name: 'Approve merge', exact: true }).isDisabled(), true);
  await page.getByLabel('Source', { exact: true }).fill('cleanup-preview-invalidation');
  await page.getByLabel('Review status', { exact: true }).selectOption('pending');
  await page.getByRole('button', { name: 'Search answers', exact: true }).click();
  await page.getByRole('button', { name: 'Is employment authorization available in the country?', exact: true }).click();
  let releaseApproval, signalApproval;
  const approvalGate = new Promise(resolve => { releaseApproval = resolve; });
  const approvalEntered = new Promise(resolve => { signalApproval = resolve; });
  await page.route('**/api/answers/cleanup-approve', async route => { signalApproval(); await approvalGate; await route.continue(); });
  page.once('dialog', dialog => dialog.accept());
  await panel.getByRole('button', { name: 'Approve merge', exact: true }).click();
  await approvalEntered;
  await page.locator('fieldset[disabled]').waitFor();
  assert.equal(await page.getByLabel('Question', { exact: true }).isDisabled(), true);
  releaseApproval();
  await page.getByText('Answers merged.', { exact: true }).waitFor();
  await page.unroute('**/api/answers/cleanup-approve');
  assert.equal(await page.getByLabel('Question', { exact: true }).count(), 0);
  const merged = JSON.parse(await readFile(join(root, 'answers.json'), 'utf8'));
  assert.equal(merged.answers['cleanup-winner'].revision, 2);
  assert.equal(merged.answers['cleanup-winner'].value, 'PRIVATE-CLEANUP-BROWSER');
  assert.equal(Object.values(merged.answers).some(answer => answer.question === 'Is employment authorization available in the country?'), false);
  assert.ok(Object.values(merged.redirects).some(redirect => redirect.targetKey === 'cleanup-winner'));
  await page.getByRole('button', { name: 'Preview cleanup', exact: true }).click();
  await panel.getByText('No clear duplicates found.', { exact: true }).waitFor();
  return { approval: true, declinedConfirmation: true, dirtyApprovalGuard: true, proposals: true, empty: true, retry: true, valueFree: true, noMutation: true, saveInvalidation: true, narrow: true };
}
