import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { join } from 'node:path';
const execute=promisify(execFile);
export async function nativeFactsBrowser(page,root,fixture,buildRoot) {
  await page.getByRole('button',{name:'Close job details'}).click();
  await page.getByRole('button',{name:'Facts',exact:true}).click();
  await page.getByText('No profile facts yet.',{exact:false}).waitFor();
  await page.getByLabel('Fact name',{exact:true}).fill('custom');
  await page.getByLabel('Value type').selectOption('null');
  await page.getByLabel('Fact name',{exact:true}).fill('firstName');
  assert.equal(await page.getByRole('button',{name:'Add fact',exact:true}).isDisabled(),true);
  await page.getByLabel('Value type').selectOption('text');
  await page.getByRole('button',{name:'Add fact',exact:true}).click();
  await page.getByLabel('firstName',{exact:true}).fill('Browser name');
  await page.getByRole('button',{name:'Save facts',exact:true}).click();
  await page.getByText('Facts saved.',{exact:true}).waitFor();
  assert.equal(JSON.parse(await readFile(join(root,'profile.json'),'utf8')).profile.firstName,'Browser name');
  await page.getByLabel('firstName',{exact:true}).fill('Browser draft');
  const patch=join(fixture.root,'facts-patch.json');
  await writeFile(patch,'{"phone":"CLI phone","opaque":{"huge":9007199254740993,"float":1.0}}');
  await execute(process.execPath,[join(buildRoot,'runtime/cli/native-jobs.js'),'--root',root,'--native-lock',fixture.receipt.artifact,
    'profile-patch','--input',patch,'--expected-revision','2','--source','user'],{env:{PATH:''}});
  await page.getByRole('button',{name:'Save facts',exact:true}).click();
  await page.getByRole('button',{name:'Reapply my facts draft',exact:true}).waitFor();
  assert.equal(await page.getByLabel('firstName',{exact:true}).inputValue(),'Browser draft');
  await page.getByRole('button',{name:'Reapply my facts draft',exact:true}).click();
  await page.getByRole('button',{name:'Save facts',exact:true}).click();
  await page.getByText('Facts saved.',{exact:true}).waitFor();
  assert.equal(await page.getByLabel('huge',{exact:true}).inputValue(),'9007199254740993');
  assert.equal(await page.getByLabel('float',{exact:true}).inputValue(),'1.0');
  await page.getByLabel('New field in opaque',{exact:true}).fill('note');
  await page.getByRole('button',{name:'Add field to opaque',exact:true}).click();
  await page.getByLabel('note',{exact:true}).fill('Keep numeric values');
  await page.getByRole('button',{name:'Save facts',exact:true}).click();
  await page.getByText('Facts saved.',{exact:true}).waitFor();
  await page.getByLabel('huge',{exact:true}).fill('not a number');
  assert.equal(await page.getByRole('button',{name:'Save facts',exact:true}).isDisabled(),true);
  page.once('dialog',dialog=>dialog.accept());
  await page.getByRole('button',{name:'Discard facts changes',exact:true}).click();
  assert.equal(await page.getByLabel('huge',{exact:true}).inputValue(),'9007199254740993');
  await page.getByLabel('Fact name',{exact:true}).fill('preferences');
  await page.getByRole('button',{name:'Add fact',exact:true}).click();
  await page.getByLabel('New field in preferences',{exact:true}).fill('remote');
  await page.getByLabel('Type for new field in preferences',{exact:true}).selectOption('boolean');
  await page.getByRole('button',{name:'Add field to preferences',exact:true}).click();
  await page.getByRole('button',{name:'Save facts',exact:true}).click();
  await page.getByText('Facts saved.',{exact:true}).waitFor();
  assert.equal(JSON.parse(await readFile(join(root,'profile.json'),'utf8')).profile.preferences.remote,true);
  await page.getByLabel('Fact name',{exact:true}).fill('workHistory');
  await page.getByRole('button',{name:'Add fact',exact:true}).click();
  await page.getByRole('button',{name:'Add workHistory entry',exact:true}).click();
  await page.getByLabel('company',{exact:true}).fill('Synthetic employer');
  await page.getByLabel('title',{exact:true}).fill('Engineer');
  await page.getByRole('button',{name:'Save facts',exact:true}).click();
  await page.getByText('Facts saved.',{exact:true}).waitFor();
  await page.getByLabel('Group label',{exact:true}).fill('Contact');
  await page.getByLabel('Fact paths, one per line',{exact:true}).fill('/firstName\n/phone ');
  await page.getByRole('button',{name:'Save group',exact:true}).click();
  await page.getByText('Group saved.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Edit Contact',exact:true}).click();
  await page.getByLabel('Group label',{exact:true}).fill('Contact renamed');
  await page.getByRole('button',{name:'Save group',exact:true}).click();
  await page.getByRole('button',{name:'Edit Contact renamed',exact:true}).waitFor();
  const groups=JSON.parse(await readFile(join(root,'fact-groups.json'),'utf8')).groups;
  assert.deepEqual(Object.values(groups)[0].paths,['/firstName','/phone ']);
  let releaseClaim, claimRequested;
  const heldClaim = new Promise(resolve => { releaseClaim = resolve; });
  const startedClaim = new Promise(resolve => { claimRequested = resolve; });
  const holdStatus = async route => { claimRequested(); await heldClaim; await route.continue(); };
  await page.route('**/api/claims', holdStatus);
  try {
    await page.reload();
    await startedClaim;
    await page.locator('[data-job-create]:disabled').waitFor();
    // Read-only claim loading must not trigger a discard prompt or prevent navigation.
    await page.getByRole('button',{name:'Facts',exact:true}).click();
    await page.getByLabel('firstName',{exact:true}).waitFor();
  } finally {
    releaseClaim();
    await page.unroute('**/api/claims', holdStatus);
  }
  assert.equal(await page.getByLabel('firstName',{exact:true}).inputValue(),'Browser draft');
  assert.equal(await page.getByLabel('phone',{exact:true}).inputValue(),'CLI phone');
  assert.equal(await page.getByLabel('company',{exact:true}).inputValue(),'Synthetic employer');
  await page.getByRole('button',{name:'Edit Contact renamed',exact:true}).waitFor();
  const saved=await readFile(join(root,'profile.json'),'utf8');
  assert.match(saved,/9007199254740993/);assert.match(saved,/1\.0/);
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  return {profileDisk:true,cliConflict:true,reapplyReload:true,repeaters:true,groups:true,numericPreservation:true};
}
