import assert from 'node:assert/strict';

export async function projectionsBrowser(page, {jobId, markReady}) {
  const navigation = page.getByRole('navigation', {name:'Workspace sections'});
  await navigation.getByRole('button', {name:'Overview',exact:true}).click();
  await page.getByRole('heading', {name:'Your next step',exact:true}).waitFor();
  await page.getByRole('button', {name:'Open Needs Attention',exact:true}).waitFor();
  assert.equal(await page.getByRole('link', {name:'Edit Facts',exact:true}).count(),0);
  await page.getByRole('button', {name:'Manage Resumes',exact:true}).click();
  await page.getByRole('button', {name:'Import resume',exact:true}).waitFor();
  await navigation.getByRole('button', {name:'Overview',exact:true}).click();
  await page.getByRole('button', {name:'Open Needs Attention',exact:true}).waitFor();
  await page.route('**/api/overview',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":{"message":"Synthetic outage"}}'}));
  await page.getByRole('button', {name:'Refresh overview',exact:true}).click();
  await page.getByText(/Showing the last loaded overview/).waitFor();
  await page.unroute('**/api/overview');
  await page.getByRole('button', {name:'Retry overview',exact:true}).click();
  await page.getByText(/Showing the last loaded overview/).waitFor({state:'hidden'});
  await page.getByRole('button', {name:'Open Needs Attention',exact:true}).click();
  const attention = page.getByRole('region', {name:'Needs Attention',exact:true});
  await attention.getByRole('button', {name:`Open job ${jobId}`,exact:true}).waitFor();
  await attention.getByLabel('Filter by reason').selectOption('expired_agent_attempt');
  await attention.getByText('No jobs match this reason filter.',{exact:true}).waitFor();
  await attention.getByLabel('Filter by reason').selectOption('');
  await attention.getByRole('button', {name:`Open job ${jobId}`,exact:true}).click();
  const modal = page.getByRole('dialog', {name:'Edit job',exact:true});
  await modal.waitFor();
  const activity = modal.getByRole('region',{name:'Job activity',exact:true});
  await activity.getByText(/Status: needs info/i).waitFor();
  await activity.getByText(/Job restarted/i).first().waitFor();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.route('**/api/jobs/*/activity',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}));
  await activity.getByRole('button',{name:'Refresh activity',exact:true}).click();
  await activity.getByText(/last successful snapshot for this job/).waitFor();
  await page.unroute('**/api/jobs/*/activity');
  await activity.getByRole('button',{name:'Refresh activity',exact:true}).click();
  await activity.getByText(/last successful snapshot for this job/).waitFor({state:'hidden'});
  await modal.locator('[name="notes"]').fill('Projection navigation draft');
  page.once('dialog',dialog=>dialog.dismiss());
  await modal.getByRole('button',{name:'Close job details',exact:true}).click();
  assert.equal(await modal.locator('[name="notes"]').inputValue(),'Projection navigation draft');
  page.once('dialog',dialog=>dialog.accept());
  await modal.getByRole('button',{name:'Close job details',exact:true}).click();
  await navigation.getByRole('button',{name:'Needs Attention',exact:true}).click();
  await attention.getByRole('button',{name:`Open job ${jobId}`,exact:true}).waitFor();
  await markReady();
  await attention.getByRole('button',{name:'Refresh attention',exact:true}).click();
  await attention.getByRole('button',{name:`Open job ${jobId}`,exact:true}).waitFor({state:'hidden'});
  // The preceding Answers walkthrough deliberately retains another unresolved job.
  await attention.getByRole('button',{name:'Open job pending-browser-job',exact:true}).waitFor();
  await navigation.getByRole('button',{name:'Overview',exact:true}).click();
  await page.getByRole('button',{name:'Open Needs Attention',exact:true}).waitFor();
  return {overview:true,attention:true,activity:true,staleRetry:true,resolvedAttention:true};
}
