"""Explicit-runtime Store CLI parser implementation."""

from __future__ import annotations

import argparse
from typing import Any


def build_parser(runtime: dict[str, Any]) -> argparse.ArgumentParser:
    parser = runtime['argparse'].ArgumentParser(description=runtime['__doc__'])
    parser.add_argument(
        "--root",
        help=f"store directory (default: ${runtime['STORE_ENV']} or ~/.job-apply)",
    )
    parser.add_argument("--legacy-profile", help="legacy profile path override")
    commands = parser.add_subparsers(dest="command", required=True)

    commands.add_parser("init")
    commands.add_parser("paths")
    commands.add_parser("profile-get")
    commands.add_parser("profile-inspect")
    profile_replace = commands.add_parser("profile-replace")
    profile_replace.add_argument("--input", required=True)
    profile_replace.add_argument("--expected-revision", required=True, type=int)
    profile_replace.add_argument("--source", required=True, choices=sorted(runtime['FACT_SOURCES']))
    profile_patch = commands.add_parser("profile-patch")
    profile_patch.add_argument("--input", required=True)
    profile_patch.add_argument("--expected-revision", required=True, type=int)
    profile_patch.add_argument("--source", required=True, choices=sorted(runtime['FACT_SOURCES']))
    commands.add_parser("fact-group-list")
    fact_group_get = commands.add_parser("fact-group-get")
    fact_group_get.add_argument("--id", required=True)
    fact_group_create = commands.add_parser("fact-group-create")
    fact_group_create.add_argument("--input", required=True)
    fact_group_update = commands.add_parser("fact-group-update")
    fact_group_update.add_argument("--id", required=True)
    fact_group_update.add_argument("--input", required=True)
    fact_group_update.add_argument("--expected-revision", required=True, type=int)
    fact_group_delete = commands.add_parser("fact-group-delete")
    fact_group_delete.add_argument("--id", required=True)
    fact_group_delete.add_argument("--expected-revision", required=True, type=int)
    commands.add_parser("preferences-get")
    preferences_set = commands.add_parser("preferences-set")
    preferences_set.add_argument("--input", required=True)
    preferences_set.add_argument("--expected-revision", required=True, type=int)
    preferences_set.add_argument("--source", required=True, choices=sorted(runtime['FACT_SOURCES']))
    preferences_set.add_argument("--replace", action="store_true")

    key = commands.add_parser("answer-key")
    key.add_argument("--question", required=True)
    key.add_argument("--scope", default="{}")
    put = commands.add_parser("answer-put")
    put.add_argument("--input", required=True)
    put.add_argument("--expected-revision", type=int)
    put.add_argument("--remember-sensitive", action="store_true")
    get = commands.add_parser("answer-get")
    get.add_argument("--key", required=True)
    get.add_argument("--include-trashed", action="store_true")
    find = commands.add_parser("answer-find")
    find.add_argument("--question", required=True)
    find.add_argument("--scope", default="{}")
    answer_list = commands.add_parser("answer-list")
    answer_list.add_argument("--state")
    answer_review_filter = answer_list.add_mutually_exclusive_group()
    answer_review_filter.add_argument("--review-status", choices=sorted(runtime['ANSWER_REVIEW_STATUSES']), default="accepted")
    answer_review_filter.add_argument("--all-review-statuses", action="store_true")
    answer_list.add_argument("--query", default="")
    answer_list.add_argument("--offset", type=int, default=0)
    answer_list.add_argument("--limit", type=int, default=50)
    answer_list.add_argument("--include-trashed", action="store_true")
    answer_list.add_argument("--trashed-only", action="store_true")
    answer_reveal = commands.add_parser("answer-reveal")
    answer_reveal.add_argument("--key", required=True)
    answer_observe = commands.add_parser("answer-observe")
    answer_observe.add_argument("--input", required=True)
    answer_review = commands.add_parser("answer-review")
    answer_review.add_argument("--key", required=True)
    answer_review.add_argument("--decision", required=True, choices=["accepted", "declined"])
    answer_review.add_argument("--expected-revision", required=True, type=int)
    answer_review.add_argument("--input")
    answer_review.add_argument("--remember-sensitive", action="store_true")
    answer_update = commands.add_parser("answer-update")
    answer_update.add_argument("--key", required=True)
    answer_update.add_argument("--input", required=True)
    answer_update.add_argument("--expected-revision", required=True, type=int)
    answer_update.add_argument("--remember-sensitive", action="store_true")
    answer_trash = commands.add_parser("answer-trash")
    answer_trash.add_argument("--key", required=True)
    answer_trash.add_argument("--expected-revision", required=True, type=int)
    answer_restore = commands.add_parser("answer-restore")
    answer_restore.add_argument("--key", required=True)
    answer_restore.add_argument("--expected-revision", required=True, type=int)
    answer_delete = commands.add_parser("answer-delete")
    answer_delete.add_argument("--key", required=True)
    answer_delete.add_argument("--expected-revision", required=True, type=int)
    answer_merge = commands.add_parser("answer-merge")
    answer_merge.add_argument("--winner-key", required=True)
    answer_merge.add_argument("--source-key", required=True)
    answer_merge.add_argument("--expected-winner-revision", required=True, type=int)
    answer_merge.add_argument("--expected-source-revision", required=True, type=int)
    semantic_lookup = commands.add_parser("answer-semantic-lookup")
    semantic_lookup.add_argument("--input", required=True)
    commands.add_parser("answer-cleanup-preview")
    cleanup_approve = commands.add_parser("answer-cleanup-approve")
    cleanup_approve.add_argument("--input", required=True)
    cleanup_approve.add_argument("--owner-confirmed", action="store_true")

    job_create = commands.add_parser("job-create")
    job_create.add_argument("--input", required=True)
    job_create.add_argument("--origin", choices=sorted(runtime['JOB_ORIGINS']), default="human")
    job_upsert_preview = commands.add_parser("job-upsert-preview")
    job_upsert_preview.add_argument("--input", required=True)
    job_upsert_preview.add_argument("--origin", choices=sorted(runtime['JOB_ORIGINS']), required=True)
    job_upsert_commit = commands.add_parser("job-upsert-commit")
    job_upsert_commit.add_argument("--input", required=True)
    job_upsert_commit.add_argument("--origin", choices=sorted(runtime['JOB_ORIGINS']), required=True)
    job_upsert_commit.add_argument("--token", required=True)
    legacy_jobs_preview = commands.add_parser("legacy-jobs-preview")
    legacy_jobs_preview.add_argument("--select", action="append", default=[])
    legacy_jobs_commit = commands.add_parser("legacy-jobs-commit")
    legacy_jobs_commit.add_argument("--select", action="append", required=True)
    legacy_jobs_commit.add_argument("--confirm", required=True)
    job_get = commands.add_parser("job-get")
    job_get.add_argument("--id", required=True)
    job_get.add_argument("--include-trashed", action="store_true")
    job_list = commands.add_parser("job-list")
    job_list.add_argument("--status")
    job_list.add_argument("--include-trashed", action="store_true")
    job_list.add_argument("--trashed-only", action="store_true")
    job_preflight = commands.add_parser("job-preflight")
    job_preflight.add_argument("--id", required=True)
    job_update = commands.add_parser("job-update")
    job_update.add_argument("--id", required=True)
    job_update.add_argument("--input", required=True)
    job_update.add_argument("--expected-revision", required=True, type=int)
    job_update.add_argument("--origin", choices=sorted(runtime['JOB_ORIGINS']), default="human")
    job_transition = commands.add_parser("job-transition")
    job_transition.add_argument("--id", required=True)
    job_transition.add_argument("--status", required=True)
    job_transition.add_argument("--closed-outcome")
    job_transition.add_argument("--expected-revision", required=True, type=int)
    job_transition.add_argument("--user-confirmed", action="store_true")
    job_acquire = commands.add_parser("job-acquire")
    job_acquire.add_argument("--id", required=True)
    job_acquire.add_argument("--owner", required=True)
    job_acquire.add_argument("--expected-revision", required=True, type=int)
    job_review_restart = commands.add_parser("job-review-restart")
    job_review_restart.add_argument("--id", required=True)
    job_review_restart.add_argument("--owner", required=True)
    job_review_restart.add_argument("--expected-revision", required=True, type=int)
    job_review_restart.add_argument(
        "--owner-confirmed-not-submitted", action="store_true"
    )
    commands.add_parser("claim-status")
    claim_heartbeat = commands.add_parser("claim-heartbeat")
    claim_heartbeat.add_argument("--id", required=True)
    claim_heartbeat.add_argument("--token", required=True)
    claim_recover = commands.add_parser("claim-recover")
    claim_recover.add_argument("--id", required=True)
    claim_recover.add_argument("--owner", required=True)
    claim_progress = commands.add_parser("claim-progress")
    claim_progress.add_argument("--id", required=True)
    claim_progress.add_argument("--token", required=True)
    claim_progress.add_argument("--input", required=True)
    claim_handoff = commands.add_parser("claim-handoff")
    claim_handoff.add_argument("--id", required=True)
    claim_handoff.add_argument("--token", required=True)
    claim_handoff.add_argument("--status", required=True)
    claim_handoff.add_argument("--input", required=True)
    claim_handoff.add_argument("--expected-revision", required=True, type=int)
    approval_preview = commands.add_parser("attention-approval-preview")
    approval_preview.add_argument("--id", required=True)
    approval_preview.add_argument("--expected-job-revision", required=True, type=int)
    approval_preview.add_argument("--expected-session-revision", required=True, type=int)
    approval_preview.add_argument("--input", required=True)
    approval_commit = commands.add_parser("attention-approval-approve")
    approval_commit.add_argument("--id", required=True)
    approval_commit.add_argument("--expected-job-revision", required=True, type=int)
    approval_commit.add_argument("--expected-session-revision", required=True, type=int)
    approval_commit.add_argument("--preview-token", required=True)
    approval_commit.add_argument("--input", required=True)
    approval_commit.add_argument("--owner-confirmed", action="store_true")
    job_trash = commands.add_parser("job-trash")
    job_trash.add_argument("--id", required=True)
    job_trash.add_argument("--expected-revision", required=True, type=int)
    job_restore = commands.add_parser("job-restore")
    job_restore.add_argument("--id", required=True)
    job_restore.add_argument("--expected-revision", required=True, type=int)
    job_delete = commands.add_parser("job-delete")
    job_delete.add_argument("--id", required=True)
    job_delete.add_argument("--expected-revision", required=True, type=int)

    resume_create = commands.add_parser("resume-create")
    resume_create.add_argument("--input", required=True)
    resume_import = commands.add_parser("resume-import")
    resume_import.add_argument("--input", required=True)
    resume_get = commands.add_parser("resume-get")
    resume_get.add_argument("--id", required=True)
    resume_get.add_argument("--include-trashed", action="store_true")
    resume_resolve = commands.add_parser("resume-resolve")
    resume_resolve.add_argument("--id")
    resume_list = commands.add_parser("resume-list")
    resume_list.add_argument("--include-trashed", action="store_true")
    resume_list.add_argument("--trashed-only", action="store_true")
    resume_update = commands.add_parser("resume-update")
    resume_update.add_argument("--id", required=True)
    resume_update.add_argument("--input", required=True)
    resume_update.add_argument("--expected-revision", required=True, type=int)
    resume_adopt = commands.add_parser("resume-adopt")
    resume_adopt.add_argument("--id", required=True)
    resume_adopt.add_argument("--expected-revision", required=True, type=int)
    resume_adopt.add_argument("--path")
    resume_default = commands.add_parser("resume-set-default")
    resume_default.add_argument("--id", required=True)
    resume_default.add_argument("--expected-revision", required=True, type=int)
    resume_check = commands.add_parser("resume-check")
    resume_check.add_argument("--id", required=True)
    resume_trash = commands.add_parser("resume-trash")
    resume_trash.add_argument("--id", required=True)
    resume_trash.add_argument("--expected-revision", required=True, type=int)
    resume_restore = commands.add_parser("resume-restore")
    resume_restore.add_argument("--id", required=True)
    resume_restore.add_argument("--expected-revision", required=True, type=int)
    resume_delete = commands.add_parser("resume-delete")
    resume_delete.add_argument("--id", required=True)
    resume_delete.add_argument("--expected-revision", required=True, type=int)
    request_create = commands.add_parser("resume-extraction-request-create")
    request_create.add_argument("--resume-id", required=True)
    request_create.add_argument("--expected-resume-revision", required=True, type=int)
    request_get = commands.add_parser("resume-extraction-request-get")
    request_get.add_argument("--id", required=True)
    request_list = commands.add_parser("resume-extraction-request-list")
    request_list.add_argument("--resume-id")
    request_list.add_argument("--status", choices=sorted(runtime['EXTRACTION_REQUEST_STATUSES']))
    request_cancel = commands.add_parser("resume-extraction-request-cancel")
    request_cancel.add_argument("--id", required=True)
    request_cancel.add_argument("--expected-revision", required=True, type=int)
    request_fail = commands.add_parser("resume-extraction-request-fail")
    request_fail.add_argument("--id", required=True)
    request_fail.add_argument(
        "--reason", required=True, choices=sorted(runtime['EXTRACTION_REQUEST_FAILURE_REASONS'])
    )
    request_fail.add_argument("--expected-revision", required=True, type=int)
    request_retry = commands.add_parser("resume-extraction-request-retry")
    request_retry.add_argument("--id", required=True)
    request_retry.add_argument("--expected-revision", required=True, type=int)
    request_retry.add_argument("--expected-resume-revision", required=True, type=int)
    request_complete = commands.add_parser("resume-extraction-request-complete")
    request_complete.add_argument("--id", required=True)
    request_complete.add_argument("--input", required=True)
    request_complete.add_argument("--expected-request-revision", required=True, type=int)
    request_complete.add_argument("--expected-profile-revision", required=True, type=int)
    request_complete.add_argument("--expected-pending-proposal-id")
    commands.add_parser("profile-preparedness-get")
    proposal_create = commands.add_parser("resume-proposal-create")
    proposal_create.add_argument("--resume-id", required=True)
    proposal_create.add_argument("--expected-resume-revision", required=True, type=int)
    proposal_create.add_argument("--expected-profile-revision", required=True, type=int)
    proposal_create.add_argument("--supersedes")
    proposal_create.add_argument("--input", required=True)
    proposal_get = commands.add_parser("resume-proposal-get")
    proposal_get.add_argument("--id", required=True)
    proposal_list = commands.add_parser("resume-proposal-list")
    proposal_list.add_argument("--resume-id")
    proposal_list.add_argument("--status")
    proposal_list.add_argument("--summary-only", action="store_true")
    proposal_review = commands.add_parser("resume-proposal-review")
    proposal_review.add_argument("--id", required=True)
    proposal_review.add_argument("--expected-revision", required=True, type=int)
    proposal_review.add_argument("--expected-profile-revision", required=True, type=int)
    proposal_review.add_argument("--input", required=True)

    history_append = commands.add_parser("history-append")
    history_append.add_argument("--input", required=True)
    commands.add_parser("history-list")

    replay_transition = commands.add_parser("replay-transition")
    replay_transition.add_argument("--id", required=True)
    replay_transition.add_argument("--transition", required=True)
    replay_transition.add_argument("--ats", required=True)

    session_save = commands.add_parser("session-save")
    session_save.add_argument("--id", required=True)
    session_save.add_argument("--input", required=True)
    session_load = commands.add_parser("session-load")
    session_load.add_argument("--id", required=True)
    commands.add_parser("session-list")
    session_delete = commands.add_parser("session-delete")
    session_delete.add_argument("--id", required=True)
    commands.add_parser("automation-settings-get")
    automation_update = commands.add_parser("automation-settings-update")
    automation_update.add_argument("--input", required=True)
    automation_update.add_argument("--expected-revision", required=True, type=int)
    automation_copy_email = commands.add_parser("automation-settings-copy-profile-email")
    automation_copy_email.add_argument("--expected-profile-revision", required=True, type=int)
    automation_copy_email.add_argument("--expected-settings-revision", required=True, type=int)
    automation_capability = commands.add_parser("automation-capability")
    automation_capability.add_argument("--platform", choices=["darwin", "linux", "win32"])
    realm_resolve = commands.add_parser("account-realm-resolve")
    realm_resolve.add_argument("--url", required=True)
    commands.add_parser("employer-account-list")
    account_get = commands.add_parser("employer-account-get")
    account_get.add_argument("--realm-ref", required=True)
    account_create = commands.add_parser("employer-account-create")
    account_create.add_argument("--url", required=True)
    account_create.add_argument("--input")
    account_update = commands.add_parser("employer-account-update")
    account_update.add_argument("--realm-ref", required=True)
    account_update.add_argument("--input", required=True)
    account_update.add_argument("--expected-revision", required=True, type=int)
    account_execute = commands.add_parser("employer-account-execute-synthetic")
    account_execute.add_argument("--input", required=True)
    commands.add_parser("employer-account-operation-status")
    commands.add_parser("employer-account-operation-recover")
    trusted_approve = commands.add_parser("trusted-fill-approve")
    trusted_approve.add_argument("--input", required=True)
    trusted_status = commands.add_parser("trusted-fill-status")
    trusted_status.add_argument("--id", required=True)
    trusted_evaluate = commands.add_parser("trusted-fill-evaluate")
    trusted_evaluate.add_argument("--input", required=True)
    trusted_revoke = commands.add_parser("trusted-fill-revoke")
    trusted_revoke.add_argument("--id", required=True)
    trusted_revoke.add_argument("--expected-approval-revision", required=True, type=int)
    return parser

