#!/usr/bin/env python3
"""Generate the semantic matcher's fixed Python 3.12 / Unicode 15.0 tables.

Run with an explicit Python 3.12 interpreter. The tables separate BMP and
astral code points so each readable generated source remains below 500 lines.
"""
from pathlib import Path
import sys
import unicodedata


def ranges(predicate, start, end):
    result = []
    first = None
    for point in range(start, end):
        if predicate(chr(point)):
            if first is None:
                first = point
        elif first is not None:
            result.append((first, point - 1))
            first = None
    if first is not None:
        result.append((first, end - 1))
    return result


def main():
    if sys.version_info[:2] != (3, 12) or unicodedata.unidata_version != "15.0.0":
        raise SystemExit("requires Python 3.12 with Unicode 15.0.0")
    destination = Path(__file__).resolve().parents[3] / "src/contracts/workspace"
    predicates = {
        "assigned": lambda char: unicodedata.category(char) != "Cn",
        "alnum": str.isalnum,
    }
    for kind, predicate in predicates.items():
        for plane, start, end in (("bmp", 0, 0x10000), ("astral", 0x10000, 0x110000)):
            entries = ranges(predicate, start, end)
            lines = [
                "// Generated by tools/contracts/answer-matching/unicode.py.",
                f"// Python 3.12 / Unicode 15.0.0 {kind} ranges ({plane}).",
                "export const ranges: readonly (readonly [number, number])[] = [",
                *[f"  [0x{first:x}, 0x{last:x}]," for first, last in entries],
                "];",
            ]
            if len(lines) > 500:
                raise SystemExit("generated Unicode range module exceeds source-size limit")
            path = destination / f"answer-match-unicode-{kind}-{plane}.ts"
            path.write_text("\n".join(lines) + "\n", encoding="utf-8")
            print(f"{path.name}: {len(entries)} ranges, {len(lines)} lines")


if __name__ == "__main__":
    main()
