"""Regenerate the native Unicode 15.0 casefold table with CPython 3.12."""
import json
import unicodedata
from pathlib import Path

if unicodedata.unidata_version != '15.0.0':
    raise SystemExit('Requires Unicode 15.0.0 (CPython 3.12)')
items = [(i, chr(i).casefold()) for i in range(0x110000) if chr(i).casefold() != chr(i)]
ranges, exceptions = [], []
while items:
    point, folded = items.pop(0)
    end, stride = point, 1
    if len(folded) == 1:
        delta = ord(folded) - point
        if items and items[0][0] - point in (1, 2):
            stride = items[0][0] - point
        while items and items[0][0] == end + stride and len(items[0][1]) == 1 and ord(items[0][1]) - items[0][0] == delta:
            end = items.pop(0)[0]
    if end > point:
        ranges.append([point, end, stride, delta])
    else:
        exceptions.append([point, folded])
lines = ['// Unicode 15.0 full casefold; generated by tools/contracts/profile-facts/casefold.py.',
         'const ranges: readonly (readonly number[])[] = [']
lines += ['  ' + json.dumps(row) + ',' for row in ranges]
lines += ['];', 'const exceptions = new Map<number, string>([']
lines += ['  ' + json.dumps(row, ensure_ascii=True) + ',' for row in exceptions]
lines += [']);', 'export function casefold(value: string): string {',
          '  return [...value].map(character => {',
          '    const point = character.codePointAt(0)!;',
          '    const special = exceptions.get(point);',
          '    if (special !== undefined) return special;',
          '    for (const [start, end, stride, delta] of ranges) {',
          '      if (point >= start! && point <= end! && (point - start!) % stride! === 0) return String.fromCodePoint(point + delta!);',
          '    }', '    return character;', "  }).join('');", '}']
Path('src/contracts/workspace/casefold.ts').write_text('\n'.join(lines) + '\n')
