// Closed vocabulary shared by the Python semantic matcher.
export const reasonCodes = new Set([
  "ambiguous_tie",
  "authority_accepted_record",
  "authority_bounded_policy",
  "authority_missing",
  "authority_per_use",
  "candidate_accepted",
  "candidate_active",
  "candidate_confirmed",
  "candidate_deleted",
  "candidate_not_accepted",
  "candidate_not_confirmed",
  "cleanup_duplicate_pending",
  "cleanup_merge_proposed",
  "cleanup_winner_accepted",
  "confidence_eligible",
  "confidence_ineligible",
  "field_class_allowlisted",
  "field_class_match",
  "field_class_mismatch",
  "field_class_not_allowlisted",
  "match_exact_alias",
  "match_exact_question",
  "match_semantic_high",
  "match_semantic_uncertain",
  "mode_bounded_loose",
  "mode_strict",
  "no_semantic_match",
  "owner_confirmation_required",
  "polarity_mismatch",
  "reuse_eligible",
  "scope_match",
  "scope_mismatch",
  "sensitivity_match",
  "sensitivity_mismatch",
  "value_missing",
  "value_seen",
  "value_unseen",
]);
export const stopWords = new Set([
  "a",
  "an",
  "and",
  "applicant",
  "are",
  "as",
  "at",
  "be",
  "been",
  "being",
  "by",
  "do",
  "does",
  "for",
  "from",
  "have",
  "in",
  "is",
  "it",
  "of",
  "on",
  "or",
  "that",
  "the",
  "this",
  "to",
  "which",
  "who",
  "will",
  "with",
  "would",
  "you",
  "your",
]);
export const negations = new Set([
  "neither",
  "never",
  "no",
  "nor",
  "not",
  "without",
]);
export const synonyms: Readonly<Record<string, string>> = {
  "allow": "permission",
  "allowed": "permission",
  "authorize": "permission",
  "authorized": "permission",
  "authorization": "permission",
  "eligible": "permission",
  "eligibility": "permission",
  "permit": "permission",
  "permitted": "permission",
  "permission": "permission",
  "employ": "work",
  "employed": "work",
  "employment": "work",
  "job": "work",
  "work": "work",
  "working": "work",
  "country": "jurisdiction",
  "location": "jurisdiction",
  "nation": "jurisdiction",
  "territory": "jurisdiction",
  "sponsor": "sponsorship",
  "sponsored": "sponsorship",
  "sponsoring": "sponsorship",
  "sponsorship": "sponsorship",
  "immigration": "immigration",
  "visa": "immigration",
  "require": "require",
  "required": "require",
  "requires": "require",
  "requiring": "require",
  "need": "require",
  "needed": "require",
  "needs": "require",
  "future": "future",
  "later": "future",
  "eventually": "future",
  "current": "current",
  "currently": "current",
  "now": "current",
  "present": "current",
  "assist": "assistance",
  "assistance": "assistance",
  "help": "assistance",
  "start": "start",
  "begin": "start",
  "commence": "start",
  "available": "available",
  "availability": "available",
  "relocate": "relocate",
  "relocation": "relocate",
  "move": "relocate",
  "travel": "travel",
  "traveling": "travel",
  "travelling": "travel",
};
