// Explicit Companion API allowlist; no caller-selected upstream destinations.
export const apiRoutes = [
  ["GET","/api/claims"],
  ["POST","/api/claims/select"],
  ["POST","/api/claims/acquire"],
  ["POST","/api/claims/heartbeat"],
  ["POST","/api/claims/recover"],
  ["POST","/api/claims/progress"],
  ["POST","/api/claims/handoff"],

  [
    "GET",
    "/api/account-operation"
  ],
  [
    "GET",
    "/api/answers"
  ],
  [
    "GET",
    "/api/answers/by-key/{encodedKey}"
  ],
  [
    "GET",
    "/api/answers/cleanup-preview"
  ],
  [
    "GET",
    "/api/answers/{legacyKey}"
  ],
  [
    "GET",
    "/api/attention"
  ],
  [
    "GET",
    "/api/automation"
  ],
  [
    "GET",
    "/api/boot"
  ],
  [
    "GET",
    "/api/employer-accounts/{id}"
  ],
  [
    "GET",
    "/api/fact-groups"
  ],
  [
    "GET",
    "/api/fact-groups/{id}"
  ],
  [
    "GET",
    "/api/jobs"
  ],
  [
    "GET",
    "/api/jobs/{id}"
  ],
  [
    "GET",
    "/api/jobs/{id}/activity"
  ],
  [
    "GET",
    "/api/jobs/{id}/pending-answers/{reference}"
  ],
  [
    "GET",
    "/api/jobs/{id}/preflight"
  ],
  [
    "GET",
    "/api/overview"
  ],
  [
    "GET",
    "/api/pending-answers"
  ],
  [
    "GET",
    "/api/profile"
  ],
  [
    "GET",
    "/api/profile-preparedness"
  ],
  [
    "GET",
    "/api/resume-extraction-requests"
  ],
  [
    "GET",
    "/api/resume-proposals"
  ],
  [
    "GET",
    "/api/resume-proposals/{id}"
  ],
  [
    "GET",
    "/api/resumes"
  ],
  [
    "GET",
    "/api/resumes/trash"
  ],
  [
    "GET",
    "/api/resumes/{id}"
  ],
  [
    "GET",
    "/api/resumes/{id}/content"
  ],
  [
    "GET",
    "/api/state"
  ],
  [
    "GET",
    "/api/trash"
  ],
  [
    "GET",
    "/api/trusted-fill/{id}"
  ],
  [
    "PATCH",
    "/api/answers/by-key/{encodedKey}"
  ],
  [
    "PATCH",
    "/api/answers/{legacyKey}"
  ],
  [
    "PATCH",
    "/api/automation/settings"
  ],
  [
    "PATCH",
    "/api/employer-accounts/{id}"
  ],
  [
    "PATCH",
    "/api/fact-groups/{id}"
  ],
  [
    "PATCH",
    "/api/jobs/{id}"
  ],
  [
    "PATCH",
    "/api/profile"
  ],
  [
    "PATCH",
    "/api/resumes/{id}"
  ],
  [
    "POST",
    "/api/account-operation/execute-synthetic"
  ],
  [
    "POST",
    "/api/account-operation/recover"
  ],
  [
    "POST",
    "/api/answers"
  ],
  [
    "POST",
    "/api/answers/by-key/{encodedKey}/accept"
  ],
  [
    "POST",
    "/api/answers/by-key/{encodedKey}/decline"
  ],
  [
    "POST",
    "/api/answers/by-key/{encodedKey}/delete"
  ],
  [
    "POST",
    "/api/answers/by-key/{encodedKey}/merge"
  ],
  [
    "POST",
    "/api/answers/by-key/{encodedKey}/restore"
  ],
  [
    "POST",
    "/api/answers/by-key/{encodedKey}/reveal"
  ],
  [
    "POST",
    "/api/answers/by-key/{encodedKey}/trash"
  ],
  [
    "POST",
    "/api/answers/cleanup-approve"
  ],
  [
    "POST",
    "/api/answers/observe"
  ],
  [
    "POST",
    "/api/answers/query"
  ],
  [
    "POST",
    "/api/answers/semantic"
  ],
  [
    "POST",
    "/api/answers/{legacyKey}/accept"
  ],
  [
    "POST",
    "/api/answers/{legacyKey}/decline"
  ],
  [
    "POST",
    "/api/answers/{legacyKey}/delete"
  ],
  [
    "POST",
    "/api/answers/{legacyKey}/merge"
  ],
  [
    "POST",
    "/api/answers/{legacyKey}/restore"
  ],
  [
    "POST",
    "/api/answers/{legacyKey}/reveal"
  ],
  [
    "POST",
    "/api/answers/{legacyKey}/trash"
  ],
  [
    "POST",
    "/api/automation/realm-resolve"
  ],
  [
    "POST",
    "/api/automation/settings/copy-profile-email"
  ],
  [
    "POST",
    "/api/employer-accounts"
  ],
  [
    "POST",
    "/api/fact-groups"
  ],
  [
    "POST",
    "/api/fact-groups/{id}/delete"
  ],
  [
    "POST",
    "/api/jobs"
  ],
  [
    "POST",
    "/api/jobs/bulk"
  ],
  [
    "POST",
    "/api/jobs/{id}/approval-approve"
  ],
  [
    "POST",
    "/api/jobs/{id}/approval-preview"
  ],
  [
    "POST",
    "/api/jobs/{id}/delete"
  ],
  [
    "POST",
    "/api/jobs/{id}/resolve-pending-answer"
  ],
  [
    "POST",
    "/api/jobs/{id}/restore"
  ],
  [
    "POST",
    "/api/jobs/{id}/transition"
  ],
  [
    "POST",
    "/api/jobs/{id}/trash"
  ],
  [
    "POST",
    "/api/resume-extraction-requests"
  ],
  [
    "POST",
    "/api/resume-extraction-requests/{id}/cancel"
  ],
  [
    "POST",
    "/api/resume-extraction-requests/{id}/retry"
  ],
  [
    "POST",
    "/api/resume-proposals/{id}/review"
  ],
  [
    "POST",
    "/api/resumes/import"
  ],
  [
    "POST",
    "/api/resumes/{id}/adopt"
  ],
  [
    "POST",
    "/api/resumes/{id}/default"
  ],
  [
    "POST",
    "/api/resumes/{id}/delete"
  ],
  [
    "POST",
    "/api/resumes/{id}/replace"
  ],
  [
    "POST",
    "/api/resumes/{id}/restore"
  ],
  [
    "POST",
    "/api/resumes/{id}/trash"
  ],
  [
    "POST",
    "/api/trusted-fill/approve"
  ],
  [
    "POST",
    "/api/trusted-fill/evaluate"
  ],
  [
    "POST",
    "/api/trusted-fill/{id}/revoke"
  ]
] as const;

export function permittedApi(method: string, path: string): boolean {
  if (/%(?![0-9a-f]{2})/i.test(path)) return false;
  return apiRoutes.some(([verb, template]) => verb === method &&
    new RegExp("^" + template.replace(/\{[^}]+\}/g, "[^/]+") + "$").test(path));
}
